# Generated by Django 4.2.14 on 2025-09-06 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_gpaconfig_gradescale_studentguardian_scheduleentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Bir oylik hisob (oyning 1-kuni sifatida saqlanadi)')),
                ('amount_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('penalty_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('paid_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Toʻlanmagan'), ('partial', 'Qisman toʻlangan'), ('paid', 'Toʻlangan')], default='unpaid', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='academics.student')),
            ],
            options={
                'ordering': ['-month', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='TuitionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('clazz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_plan', to='academics.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'Oʻtkazma')], default='cash', max_length=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_no', models.CharField(blank=True, max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.student')),
            ],
            options={
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['invoice', 'paid_at'], name='billing_pay_invoice_a3e9c0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'month'], name='billing_inv_student_9299ef_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'month'], name='billing_inv_status_bbb599_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'month')},
        ),
    ]
