# Generated by Django 4.2.14 on 2025-09-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Oyning birinchi kuni sifatida saqlanadi (YYYY-MM-01)')),
                ('fio', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fio', 'date'],
                'indexes': [models.Index(fields=['month', 'fio', 'date'], name='billing_sal_month_fe8eed_idx')],
                'unique_together': {('month', 'fio', 'date')},
            },
        ),
    ]
