# Generated by Django 4.2.14 on 2025-09-22 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_salarypayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryMonthLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='salarypayout',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='salarypayout',
            name='billing_sal_month_fe8eed_idx',
        ),
        migrations.AlterUniqueTogether(
            name='salarypayout',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salarypayout',
            name='amount_uzs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarypayout',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarypayout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payouts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarypayout',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='salarypayout',
            unique_together={('month', 'user')},
        ),
        migrations.AddIndex(
            model_name='salarypayout',
            index=models.Index(fields=['month', 'user'], name='billing_sal_month_c04271_idx'),
        ),
        migrations.AddField(
            model_name='salarymonthlock',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='salarypayout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salarypayout',
            name='fio',
        ),
    ]
