# Generated by Django 4.2.14 on 2025-09-22 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_salarymonthlock_alter_salarypayout_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'O‘tkazma')], default='cash', max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Oylik to‘lov'), ('food', 'Oziq-ovqat'), ('tools', 'Asbob-uskunalar'), ('rent', 'Ijara'), ('utilities', 'Kommunal to‘lovlar'), ('transport', 'Transport'), ('marketing', 'Marketing'), ('repair', 'Taʼmirlash'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='billing_exp_date_31b117_idx'), models.Index(fields=['category'], name='billing_exp_categor_c99eaa_idx')],
            },
        ),
    ]
