# Generated by Django 4.2.14 on 2025-09-22 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_expense'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='billing_exp_date_31b117_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='billing_exp_categor_c99eaa_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Oylik to‘lov'), ('food', 'Oziq-ovqat'), ('tools', 'Asbob-uskuna'), ('utility', 'Kommunal to‘lov'), ('transport', 'Transport'), ('repair', 'Ta’mirlash'), ('other', 'Boshqa')], default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
