# Generated by Django 4.2.14 on 2025-09-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'O‘qituvchi'), ('accountant', 'Hisobchi'), ('registrar', 'Ro‘yxatga oluvchi'), ('parent', 'Ota/Ona')], default='registrar', max_length=20),
        ),
    ]
