# Generated by Django 4.2.14 on 2025-09-06 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=50)),
                ('weight_daily', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('weight_exam', models.DecimalField(decimal_places=2, default=0.3, max_digits=4)),
                ('weight_final', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=50)),
                ('p2', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('p3', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('p4', models.DecimalField(decimal_places=2, default=3.5, max_digits=4)),
                ('p5', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='academics.student')),
            ],
            options={
                'unique_together': {('student', 'guardian')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.teacher')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['clazz', 'weekday', 'start_time'], name='academics_s_clazz_i_bddb66_idx')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('term', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('daily', 'Kundalik'), ('exam', 'Imtihon'), ('final', 'Yakuniy')], default='daily', max_length=10)),
                ('score', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'subject', 'term'], name='academics_g_student_a2fce3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Kelgan'), ('absent', 'Kelmagan'), ('late', 'Kechikkan'), ('excused', 'Sababli')], default='present', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'date'], name='academics_a_student_ec0522_idx')],
                'unique_together': {('student', 'date', 'subject')},
            },
        ),
    ]
